AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Main stack that includes a custom resource

Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      RoleName: my-lambda-role

  MyRoleTags:
    Type: Custom::MyRoleTags
    Properties:
      ServiceToken: !ImportValue MyRoleTagsLambda
      RoleName: !Ref MyRole
      Tags:
        - Key: Key 1
          Value: Value 1
        - Key: Key 2
          Value: Value 2

Outputs:
  MyRoleArn:
    Value: !GetAtt MyRole.Arn
